---
- name: Install packages for population task
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - python34
    - python34-setuptools

- name: Ensure services are running
  service: "name={{ item }} state=started"
  with_items:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
    - qpidd

- name: Create config directory
  file: path="{{ ansible_user_dir }}/.config/pulp_smash" state=directory

- name: Ensure a Pulp Smash configuration file is present
  template:
    src: settings.j2
    dest: "{{ ansible_user_dir }}/.config/pulp_smash/settings.json"

- name: Populate the server
  script: populate.sh
