# rhel6 pulp 2.11.z backup
- name: Ensure expected variables
  assert:
    that:
      - remote_bkup_dir is defined
      - local_bkup_dir is defined
    msg: |
      Location of remote backup directory and local directory for backup to be copied to
      must be specified with varibales remote_bkup_dir and local_bkup_dir

- name: Install dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - dump
    - tar

- name: Stop services
  service: "name={{ item }} state=stopped"
  with_items:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
    - qpidd

- block:
    - name: Create temporary folder to copy backups into
      file: "path={{ remote_bkup_dir }} state=directory"

    - name: Copy filesystem backups to remote
      copy:
        src: "{{ local_bkup_dir }}/{{ item.value.file }}"
        dest: "{{ remote_bkup_dir }}"
      with_dict: "{{ files_to_restore }}"

    - name: Unarchive database backups
      unarchive:
        src: "{{ local_bkup_dir }}/{{ item.value.archive }}"
        dest: "{{ remote_bkup_dir }}"
      with_dict: "{{ db_to_restore }}"

    - name: Delete temp backup folder from server
      file: path={{ remote_bkup_dir }} state=absent

- name: Start services
  service: "name={{ item }} state=started"
  with_items:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
    - qpidd

