# rhel6 pulp 2.11.z backup
- name: Stop services before backup
  service: "name={{ item }} state=stopped"
  with_items:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
    - qpidd
  notify: Restart services

- block:
    - name: Create backups folder
      file: path={{ remote_bkup_dir }} state=directory

    - name: Create local backups folder
      local_action: file path={{ local_bkup_dir }} state=directory mode=0777
      when: fetch_to_localhost

    - name: Dump mongodb database
      command: "mongodump --db pulp_database --out {{ remote_bkup_dir }}/{{ db_to_bkup.mongodb.dir }}"

    - name: Archive filesystem backups
      command: "tar -cjf {{ remote_bkup_dir }}/{{ item.value.file }}.tar.bz2 {{ item.value.src_dir }}/"
      with_dict: "{{ files_to_backup }}"

    - name: Archive database backups
      archive:
        path: "{{ remote_bkup_dir }}/{{ item.value.dir }}"
        dest: "{{ remote_bkup_dir }}/{{ item.value.file }}.bz2"
        format: bz2
      with_dict: "{{ db_to_bkup }}"

    - name: Fetch filesystem backups
      fetch:
        src: "{{ remote_bkup_dir }}/{{ item.value.file }}.tar.bz2"
        dest: "{{ local_bkup_dir }}/{{ item.value.file }}.tar.bz2"
        flat: yes
      with_dict: "{{ files_to_backup }}"

    - name: Fetch database backups
      fetch:
        src: "{{ remote_bkup_dir }}/{{ item.value.file }}.bz2"
        dest: "{{ local_bkup_dir }}/{{ item.value.file }}.bz2"
        flat: yes
      with_dict: "{{ db_to_bkup }}"
      when: fetch_to_localhost

    - name: Delete temp backup folder from server
      file: path={{ remote_bkup_dir }} state=absent
      when: fetch_to_localhost
