---
# location of backup on remote
remote_bkup_dir: "/root/bkups"
local_bkup_dir/: "$PWD"
files_to_backup:
  etc_pulp:
    src_dir: /etc/pulp
    file: etc_pulp
  etc_pki_pulp:
    src_dir: /etc/pki/pulp
    file: etc_pki_pulp
  var_lib_pulp:
    src_dir: /var/lib/pulp
    file: var_lib_pulp

db_to_bkup:
  mongodb:
    dir: mongodb_backup_dir
    file: mongodb_backup
